INSERT INTO OAUTH_CLIENT_DETAILS  (
  CLIENT_ID,RESOURCE_IDS,CLIENT_SECRET,SCOPE,AUTHORIZED_GRANT_TYPES,
  AUTHORITIES,ACCESS_TOKEN_VALIDITY,REFRESH_TOKEN_VALIDITY,AUTOAPPROVE
) VALUES (
  'trusted-app','MS_UAA_SERVICE','secret','read,write','client_credentials,password,refresh_token',
  'ROLE_TRUSTED_CLIENT',3600,10000,TRUE
);

INSERT INTO OAUTH_CLIENT_DETAILS  (
  CLIENT_ID,RESOURCE_IDS,SCOPE,AUTHORIZED_GRANT_TYPES,
  AUTHORITIES,ACCESS_TOKEN_VALIDITY,REFRESH_TOKEN_VALIDITY,AUTOAPPROVE
) VALUES (
  'normal-app','MS_UAA_SERVICE','read,write','authorization_code,implicit',
  'ROLE_CLIENT',3600,10000,TRUE
);

INSERT INTO OAUTH_CLIENT_DETAILS  (
  CLIENT_ID,RESOURCE_IDS,CLIENT_SECRET,SCOPE,AUTHORIZED_GRANT_TYPES,
  AUTHORITIES,ACCESS_TOKEN_VALIDITY,REFRESH_TOKEN_VALIDITY,AUTOAPPROVE
) VALUES (
  'register-app','MS_UAA_SERVICE','secret','read','client_credentials',
  'ROLE_REGISTER',3600,10000,TRUE
);

INSERT INTO OAUTH_CLIENT_DETAILS  (
CLIENT_ID,RESOURCE_IDS,SCOPE,AUTHORIZED_GRANT_TYPES,WEB_SERVER_REDIRECT_URI,
AUTHORITIES,ACCESS_TOKEN_VALIDITY,REFRESH_TOKEN_VALIDITY,ADDITIONAL_INFORMATION,AUTOAPPROVE
) VALUES (
'my-client-with-registered-redirect','MS_UAA_SERVICE','read,trust','authorization_code','http://webfuse.cn?key=value',
'ROLE_CLIENT',3600,10000,'',TRUE
)